### ISSUE TITLE
Fast Delete Feature

### ISSUE THREAD

**Issue by PhOzz** [LGatodu47/ScreenshotViewer#21]
Screenshot viewer doesn't show screenshot with the .jpg format but only .png.
I would like to use both mods, so I request this feature.
Also, I would like the ability to delete screenshots with the delete key instead of using the right click>delete option.

(I play Minecraft 1.20.1)
**Thanks** for earing my suggestion.

**Comment by LGatodu47** [comment]
> Screenshot viewer doesn't show screenshot with the .jpg format but only .png

Following your suggestion, I implemented reading JPEG screenshots in version 1.2.1 of the mod recently.

> Also, I would like the ability to delete screenshots with the delete key instead of using the right click>delete option.

However I won't add this ability, because a single misinput would cause your screenshot to be deleted. I plan on adding a 'fast delete' option instead, where you would select the screenshots you want to delete and then click on a button to delete the selected ones. But I can't say that it will be comming soon, so as a temporary solution I recommend you click on the 'open folder' button and delete them though your file explorer.

I hope my answer was useful.

**Comment by PhOzz** [comment]
Thank you, really helpful

**Comment by LGatodu47** [comment]
Closing this one, as it is implemented in Screenshot Viewer 1.3.0
