### ISSUE TITLE
Screenshots Don't Open Up After Refresh

### ISSUE THREAD

**Issue by Talbe1** [LGatodu47/ScreenshotViewer#8]
After refreshing the screenshots browsing menu ALL of the thumbnails of screenshots and the screenshots themselves become blank.
Only a restart of the game solves the problem.

From my testing this issue affects multiple versions.
I tested version 1.1.5 (for Minecraft 1.19.4) of the mod and 1.1.1 (for Minecraft 1.18.2).
The problem could be present in more versions than what I tested.

Here's a video that shows the problem.
https://github.com/LGatodu47/ScreenshotViewer/assets/104154497/f18e60bc-ace1-4f66-aa00-63e8bdbbd445

**Comment by Talbe1** [comment]
Apart from this issue, I really, really like this mod!

**Comment by LGatodu47** [comment]
Thanks for submitting your issue! It is definitely a weird one as your screenshots load correctly the first time you open the menu. Could you provide the logs? There might be an error occuring somewhere, and I can't replicate the bug.

**Comment by Talbe1** [comment]
Here are multiple (they **could** be identical**):
1. [latest one.log](https://github.com/LGatodu47/ScreenshotViewer/files/11837605/latest.one.log)

2. [latest two.log](https://github.com/LGatodu47/ScreenshotViewer/files/11837616/latest.two.log)

**Comment by LGatodu47** [comment]
Looked into both of them and haven't found anything relevant... I might have an idea for why it happens. I compiled a beta version of Screenshot Viewer 1.1.6 for Minecraft 1.19.4 (on fabric) including a change I made, let me know if this fixes the error for you:
[screenshot_viewer-1.1.6-b1-fabric-mc1.19.4.jar.zip](https://github.com/LGatodu47/ScreenshotViewer/files/11847187/screenshot_viewer-1.1.6-b1-fabric-mc1.19.4.jar.zip)

**Comment by Talbe1** [comment]
I tested the new version and it made the problem worse.
Now not only that the screenshots appear blank after pressing on the refresh button, but when opening the same interface for the second time they become blank too.

I'll provide a log and a video for each run.
Run one (shows the re-opening problem):
Video:
https://github.com/LGatodu47/ScreenshotViewer/assets/104154497/22a406d3-73d7-4b26-8646-87b331d20fef

Log: [latest run one.log](https://github.com/LGatodu47/ScreenshotViewer/files/11847911/latest.run.one.log)


Run two (shows that the refresh problem still occurs):
Video:
https://github.com/LGatodu47/ScreenshotViewer/assets/104154497/5770c79d-a798-4cd0-859b-68547650aa24

Log: [latest run two.log](https://github.com/LGatodu47/ScreenshotViewer/files/11847915/latest.run.two.log)



Note: I think that the logs are the same again, despite that they were generated in different times.

**Comment by LGatodu47** [comment]
Okay at least something changed so I now have an idea of what the problem might be. As I can't replicate it, I would like you to test 2 different versions and tell me if the bug still happens or if something differs:

- Version 1.0.0 for Minecraft **1.19.2** with fabric; this version is different from the others as it loads all screenshots at once causing huge lag when opening the screen/refreshing, and I wonder if it will make any difference on your side. Here's the file:
[screenshot_viewer-1.0.0-fabric-1.19.2.jar.zip](https://github.com/LGatodu47/ScreenshotViewer/files/11848310/screenshot_viewer-1.0.0-fabric-1.19.2.jar.zip)

- Another beta of version 1.1.6 I compiled with again some changes:
[screenshot_viewer-1.1.6-b2-fabric-mc1.19.4.jar.zip](https://github.com/LGatodu47/ScreenshotViewer/files/11848539/screenshot_viewer-1.1.6-b2-fabric-mc1.19.4.jar.zip)

In my opinion this bug is caused by synchronization not done correctly causing reloaded screenshots images to be immediately closed and therefore showing nothing. However nothing proves that it is actually the case, it might be caused by a bug somewhere else.

**Comment by Talbe1** [comment]
I tried both of these versions and the game just freezes completely when pressing on the screenshot viewer button in the home screen (and pause menu too). Basically, the game crashed instantly.

And again, here are some not so useful logs (tell me if you don't want any more logs):
[latest 1.1.6-b2.log](https://github.com/LGatodu47/ScreenshotViewer/files/11851431/latest.1.1.6-b2.log)
[latest 1.0.0.log](https://github.com/LGatodu47/ScreenshotViewer/files/11851432/latest.1.0.0.log)

**Comment by Talbe1** [comment]
Could this issue be specific to my computer? Despite it affecting different versions.

**Comment by Talbe1** [comment]
I will test the 1.1.1 version that was made for Forge, maybe it has to do with the mod loader or API itself (such as Fabric API).
After testing I'll update this comment.

**Comment by LGatodu47** [comment]
> I tried both of these versions and the game just freezes completely when pressing on the screenshot viewer button in the home screen (and pause menu too). Basically, the game crashed instantly.

The lag happens because you seemed to have a lot of screenshots. The game takes more time to load them which might lead to a crash. I haven't thought about this but have you tried moving your screenshots temporarely in another folder and refreshing with only a few ones ? I'm curious to know if it will change anything.

> Could this issue be specific to my computer? Despite it affecting different versions.

This could be the case, as you are the first to report this issue, and my mod was downloaded quite a lot (especially on Curseforge).

> Could it be related to some line of code of the refresh functionality that was not ported properly to Fabric?

Well the weird thing is that the mod was initially made on Fabric and then ported on Forge, but now that I take a look at it, it seems that one line in particular is different, but I highly doubt that it is causing the issue.

**Comment by Talbe1** [comment]
I encountered the mentioned lag in one of the previous beta versions that you sent, but in the last two, the game just freezes completely, I was waiting 30 seconds, even a minute, and there was no response.

**Comment by LGatodu47** [comment]
Here's a last build where I made the code for refreshing screenshots identical to the forge version:
[screenshot_viewer-1.1.6-b3-fabric-mc1.19.4.jar.zip](https://github.com/LGatodu47/ScreenshotViewer/files/11852396/screenshot_viewer-1.1.6-b3-fabric-mc1.19.4.jar.zip)

Other than that I have no idea what could cause the issue on Fabric, so I cannot help you further.

**Comment by Talbe1** [comment]
The problem still persists (the screenshots appear blank after refreshing).
I'm really sorry for causing all of the hassle to you, as it looks like it's something specific that has to do with my system.
I tried making sure it wasn't my own problem before contacting you, but my effort wasn't enough.
You should not put any more time on this, it likely won't help.
